name: Docker Image CI
on:
  push:
    tags:
       - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Docker Build
        run: docker build . --cache-from ${{ secrets.DOCKERHUB_REPO }}:latest --file Dockerfile --tag ${{ secrets.DOCKERHUB_REPO }}:${{steps.tag.outputs.tag}}
      - name: Docker Tag
        run: docker tag ${{ secrets.DOCKERHUB_REPO }}:${{steps.tag.outputs.tag}}  ${{ secrets.DOCKERHUB_REPO }}:latest
      - name: Docker push version
        run: docker push ${{ secrets.DOCKERHUB_REPO }}:${{steps.tag.outputs.tag}}
      - name: Docker push and update latest
        run: docker push ${{ secrets.DOCKERHUB_REPO }}:latest